### ISSUE TITLE
The provided demo matrix fails to load

### ISSUE THREAD

**Issue by Kinantb** [benanne/wmf#1]
Hello,
I was trying to use your code on the supposedly pickled file you have linked. But I am getting the error message "IOError: Failed to interpret file 'test_matrix.pkl' as a pickle". 
Could you please at least provide some information about the underlying matrix structure so that I could create my own?

**Comment by benanne** [comment]
Have you tried redownloading it? Maybe the file was corrupted. It works for me.

It should be a scipy.sparse sparse matrix in CSR format.

**Comment by Kinantb** [comment]
Thank you for your reply. 
For some reason it worked after I updated numpy to the latest version. It also worked with the scipy.load function.
